sudo: false
language: node_js
node_js:
  - 'node'
  - 'lts/*'
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: dist
